In [3]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [4]:
import numpy as np


In [7]:
data = [[1,2], [3, 4]] # 2*2 
print(data)
# list to tensor
x_data = torch.tensor(data)
print(x_data)

[[1, 2], [3, 4]]
tensor([[1, 2],
        [3, 4]])


In [10]:
# list to numpy
np_array = np.array(data)
print(data)

# numpy to tensor
x_np = torch.from_numpy(np_array)
print(x_np)

[[1, 2], [3, 4]]
tensor([[1, 2],
        [3, 4]])


In [12]:
x_ones = torch.ones_like(x_data) # 텐서의 모양은 유지하면서 1을 채움
print(f"Ones Tensor: \n {x_ones}\n")

x_rand = torch.rand_like(x_data, dtype = torch.float)
print(f"Random Tensor: \n{x_rand} \n") # 텐서 모양 유지하면서 랜덤값 

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]])

Random Tensor: 
tensor([[0.3306, 0.9342],
        [0.6203, 0.6182]]) 



In [15]:
shape = (2,3,)
rand_tensor = torch.rand(shape) # 주어진 shape에 맞게 random 값
ones_tensor = torch.ones(shape) # 주어진 shape에 맞게 1 채워넣음 
zeros_tensor = torch.zeros(shape) # 주어진 shape에 맞게 0 채워넣음 

print('rand_tensor: ', rand_tensor)
print('ones_tensor: ', ones_tensor)
print('zeros_tensor: ', zeros_tensor)



rand_tensor:  tensor([[0.9729, 0.1259, 0.2731],
        [0.7397, 0.2423, 0.2492]])
ones_tensor:  tensor([[1., 1., 1.],
        [1., 1., 1.]])
zeros_tensor:  tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Tensor Attribute, Operation

In [18]:
tensor = torch.rand(3,4) # 3* 4 tensor 생성
print(tensor)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")


tensor([[0.7445, 0.9261, 0.5636, 0.0235],
        [0.5598, 0.4752, 0.9852, 0.4492],
        [0.3901, 0.3106, 0.7862, 0.4238]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [19]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [20]:
print(f"Device tensor is stored on: {tensor.device}")

Device tensor is stored on: cpu


In [28]:
tensor = torch.ones(4,3)
print(f"First row: {tensor[0]}")
print(f"First column {tensor[:, 0]}")
print(f"Last column: {tensor[:, -1]}")
tensor[:, 1] = 0
print(tensor)
print(f"Last column: {tensor[:, 1]}")

First row: tensor([1., 1., 1.])
First column tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])
Last column: tensor([0., 0., 0., 0.])


In [33]:
t1 = torch.cat([tensor, tensor, tensor], dim=-1)
print(t1)

tensor([[1., 0., 1., 1., 0., 1., 1., 0., 1.],
        [1., 0., 1., 1., 0., 1., 1., 0., 1.],
        [1., 0., 1., 1., 0., 1., 1., 0., 1.],
        [1., 0., 1., 1., 0., 1., 1., 0., 1.]])
